export enum ConfigEnum {
  DATA_HOST = 'DATA_HOST',
  DATA_PORT = 'DATA_PORT',
  DATA_USERNAME = 'DATA_USERNAME',
  DATA_PASSWORD = 'DATA_PASSWORD',
  DATA_BASE = 'DATA_BASE',
}

export enum LogsEnum {
  LOG_ON = 'LOG_ON',
  LOG_LEVEL = 'LOG_LEVEL',
}

export enum RedisEnum {
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
}

export enum OSSEnum {
  OSS_ACCESS_KEY_ID = 'OSS_ACCESS_KEY_ID',
  OSS_ACCESS_KEY_SECRET = 'OSS_ACCESS_KEY_SECRET',
}
